### ISSUE TITLE
xml.itemdb items

### ISSUE THREAD

**Issue by NullMouse** [shaggyze/uotiara#1]
Hey I had a issue that I was hoping you might be able to assist with, the new items from the fishing event are popping up with their XML database numbers and I'm not sure how to fix it. I tried searching through old forum posts on mabimods and a lot of them say something to the effect of delete your XML folder or unpack and repack but nothing I'm trying from there seems to be working.

**Comment by shaggyze** [comment]
there are two XML folders to delete data\xml\ and data\local\xml\ though to be specific it's itemdb.english.txt and if you are using mabipacker and checking build uotiara.pack at the end you will also need to delete uotiara.pack and language.pack in the package folder to revert back to using mabi's default xml's.
if the problem still persists chances are it's an error on nexon's end.

**Comment by NullMouse** [comment]
> there are two XML folders to delete data\xml\ and data\local\xml\ though to be specific it's itemdb.english.txt and if you are using mabipacker and checking build uotiara.pack at the end you will also need to delete uotiara.pack and language.pack in the package folder to revert back to using mabi's default xml's.
> if the problem still persists chances are it's an error on nexon's end.

Worked like a dream man thank you
