### ISSUE TITLE
[BUG] Error upon starting the game

### ISSUE THREAD

**Issue by Lystenn** [shaggyze/uotiara#9]
Attempting to open the game via the Nexon Launcher gives me an error window and the game refuses to launch.

**To Reproduce**

Install Tiara - (not including kanan or abyss)
Let it create the uotiara_00001.it at the end

1. Go to Mabinogi on the Nexon Launcher
2. Click on PLAY
3. See error

**Screenshots**

![csrss_2024-08-13_20-34-53](https://github.com/user-attachments/assets/12af04a5-000d-4266-a3f6-18f1b9369b1e)

**Desktop (please complete the following information):**

 - Operating System: Windows
 - Browser: Firefox
 - Version: win11

**Comment by shaggyze** [comment]
Do a game repair with Nexon Launcher and ensure Lib-loader is disabled under tools on components page of installer.

**Comment by Lystenn** [comment]
> Do a game repair with Nexon Launcher and ensure Lib-loader is disabled under tools on components page of installer.

wow fast response lol. that fixed it! thanks so much ♥
